name: Label Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    name: "Label Pull Request"
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: ./.github/workflows/reusable-pr-label-by-branch.yml
    secrets: inherit # pragma: allowlist secret
