name: Pre-Commit Checks

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ main ]

jobs:
  pre-commit:
    name: Pre-Commit Checks
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: ./.github/workflows/reusable-pre-commit-checks.yml
