name: Create and Publish Release

on:
  workflow_call:
    inputs:
      config_name:
        type: string
        description: "The name of the release drafter config file to use. Default:
          release-drafter.yml"
        required: false
        default: "release-drafter.yml"
      commitish:
        type: string
        description: "The release target, i.e. branch or commit it should point to.
          Default: main"
        required: false
        default: "main"
      latest:
        type: boolean
        description: "Whether this should be marked as the latest release. Default: true"
        required: false
        default: true
      disable_autolabeler:
        type: boolean
        description: "Whether to disable the autolabeler. Autolabeler should remain
          disabled if you label the pull requests with another workflow.
          Default: true"
        required: false
        default: true
      prerelease_identifier:
        type: string
        description: "The identifier to use for prereleases, e.g. \"beta\" or \"rc\". If
          this is set, the release will be marked as a prerelease and the tag
          name will be suffixed with this identifier. Default: empty string"
        required: false
        default: ""
      publish:
        type: boolean
        description: "Whether to publish the release immediately. If false, the release
          will be created as a draft. Default: true"
        required: false
        default: true
    outputs:
      release_version:
        description: "The version of the release that was created by this workflow. This
          is the tag name of the release."
        value: ${{ jobs.create-release.outputs.release_version }}

jobs:
  create-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.release-drafter.outputs.tag_name }}
    steps:
      - uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7
        id: release-drafter
        with:
          config-name: ${{ inputs.config_name }}
          commitish: ${{ inputs.commitish }}
          disable-autolabeler: ${{ inputs.disable_autolabeler }}
          publish: ${{ inputs.publish }}
          prerelease-identifier: ${{ inputs.prerelease_identifier }}
          latest: ${{ inputs.latest }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
