name: Plan Terragrunt Environment in Azure

on:
  workflow_call:
    inputs:
      git_branch:
        description: "Branch triggering this plan"
        required: true
        type: string
      tf_version:
        description: "Version of Terraform to utilize"
        required: true
        default: "1.5.5"
        type: string
      tg_version:
        description: "Version of Terragrunt to utilize"
        required: true
        default: "0.77.22"
        type: string
      environments_root:
        description: "Root folder containing all environments"
        required: false
        default: "platform"
        type: string
      environment:
        description: "Environment (subfolder of environments_root, e.g. test) to plan"
        required: true
        type: string
      region:
        description: "Region within the environment (e.g. eastus2) to plan"
        required: true
        type: string
      env_id:
        description: "Instance within the region (e.g. 000) to plan"
        required: true
        type: string
      before_plan_commands:
        description: "Commands to run prior to executing Terragrunt plan."
        required: false
        type: string
        default: ""
      after_plan_commands:
        description: "Commands to run after executing Terragrunt plan."
        required: false
        type: string
        default: ""
    secrets:
      TERRAGRUNT_DEPLOY_AZURE_CLIENT_ID:
        required: true
      TERRAGRUNT_DEPLOY_AZURE_TENANT_ID:
        required: true
      TERRAGRUNT_DEPLOY_AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: "Plan ${{ inputs.environment }}/${{ inputs.region }}/${{ inputs.env_id }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Azure Login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
        with:
          client-id: ${{ secrets.TERRAGRUNT_DEPLOY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TERRAGRUNT_DEPLOY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TERRAGRUNT_DEPLOY_AZURE_SUBSCRIPTION_ID }}

      - name: "Set default Terraform Tags"
        id: set-tags
        run: |
          set -x
          repo=$(echo "${{ github.repository }}" | cut -d "/" -f 2)
          echo "SYSTEM_TAGS={\"Organization\":\"${{ github.repository_owner }}\",\"Repository\":\"$repo\",\"Branch\":\"${{ inputs.git_branch }}\",\"CommitHash\":\"${{ github.sha }}\"}" >> "$GITHUB_OUTPUT"

      - name: Configure Mise
        id: configure-mise
        uses: launchbynttdata/launch-workflows/.github/actions/terragrunt-configure-mise@0.15.4
        with:
          tf_version: ${{ inputs.tf_version }}
          tg_version: ${{ inputs.tg_version }}

      - name: Plan
        id: plan
        uses: gruntwork-io/terragrunt-action@4ed5b7344c80315e5357f28f36159fc980bc2d5a
        env:
          INPUT_PRE_EXEC_0: |
            ${{ inputs.before_plan_commands }}
          INPUT_POST_EXEC_0: |
            ${{ inputs.after_plan_commands }}
          ARM_CLIENT_ID: ${{ secrets.TERRAGRUNT_DEPLOY_AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TERRAGRUNT_DEPLOY_AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TERRAGRUNT_DEPLOY_AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
          TF_VAR_system_tags: ${{ steps.set-tags.outputs.SYSTEM_TAGS }}
        with:
          tg_dir: "${{inputs.environments_root}}/${{ inputs.environment }}/${{
            inputs.region }}/${{ inputs.env_id }}"
          tg_command: "plan"
